### PR TITLE
Swift 3 Conversion

### PR DESCRIPTION
**Pull request by erikkerber**
Hey!

Wanted to tinker around with you Mandelbrot set - thanks for making it! This is an attempt to bring it up to Swift 3. It doesn't... "work", meaning the playground runs but the output looks nothing like a Mandelbrot set :).

Nonetheless, I've exhausted my (lack of) knowledge in Metal and pointer-based Swift.

Hopefully this is of some help.

screen shot 2016-08-28 at 12 01 06 pm

¯\_(ツ)_/¯

### CODE REVIEW

**Comment by jtbandes** [comment]
Thanks, I'm really glad you've enjoyed the playground!

I'm not really sure about the UnsafePointer stuff either — I haven't used the new APIs yet. I'll tinker with it and see what I can do. It looks like Xcode's "Convert to latest Swift syntax" is working pretty well so far...

**Comment by jtbandes** [comment]
Hmmm, I actually can't reproduce that issue on my machine... it seems to work fine.

**Comment by erikkerber** [comment]
Ah yes I should have followed up. My issue reproduces on master/Xcode 7.3 so it's not related to the conversion. I use a 2013 Mac Pro, FWIW. 

I have a recent iMac in the office - I'll see if it reproduces there.

**Comment by erikkerber** [comment]
Last update: I "quit a bunch of apps" and it started rendering properly.

Meh? ¯\_(ツ)_/¯

**Comment by jtbandes** [comment]
😳

**Comment by jtbandes** [comment]
I've just pushed an update, 6bae408fcfa08dee4440abed2b4d09bb5f3460a2, for Swift 3. Thanks for your help!

**Pull request closed without merging**
